### ISSUE TITLE
How to wipe .julia/conda?

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaPy/Conda.jl#138]
I tried deleting `.julia/conda` and re-adding Conda, but it doesn't work:
```julia
julia> using PyPlot
SYSTEM: show(lasterr) caused an error
ErrorException("error compiling display_error: error compiling findprev: error compiling lookup: error compiling Type: could not load library \"/Users/sheehanolver/.julia/conda/3/lib/libpython3.7m.dylib\"\ndlopen(/Users/sheehanolver/.julia/conda/3/lib/libpython3.7m.dylib, 1): image not found")

Stacktrace:
 [1] _include_from_serialized(::String, ::Array{Any,1}) at ./loading.jl:633
 [2] macro expansion at ./logging.jl:310 [inlined]
 [3] _require_search_from_serialized(::Base.PkgId, ::String) at ./loading.jl:704
 [4] _tryrequire_from_serialized(::Base.PkgId, ::UInt64, ::String) at ./loading.jl:648
 [5] _require_search_from_serialized(::Base.PkgId, ::String) at ./loading.jl:702
 [6] _require(::Base.PkgId) at ./loading.jl:937
 [7] require(::Base.PkgId) at ./loading.jl:858
 [8] macro expansion at ./logging.jl:309 [inlined]
 [9] require(::Module, ::Symbol) at ./loading.jl:840
 [10] eval(::Module, ::Any) at ./boot.jl:319
 [11] eval_user_input(::Any, ::REPL.REPLBackend) at /Users/sheehanolver/Projects/julia/usr/share/julia/stdlib/v1.0/REPL/src/REPL.jl:85
 [12] macro expansion at /Users/sheehanolver/Projects/julia/usr/share/julia/stdlib/v1.0/REPL/src/REPL.jl:117 [inlined]
 [13] (::getfield(REPL, Symbol("##28#29")){REPL.REPLBackend})() at ./task.jl:259
fatal: error thrown and no exception handler available.
ErrorException("error compiling display_error: error compiling findprev: error compiling lookup: error compiling Type: could not load library "/Users/sheehanolver/.julia/conda/3/lib/libpython3.7m.dylib"
dlopen(/Users/sheehanolver/.julia/conda/3/lib/libpython3.7m.dylib, 1): image not found")
rec_backtrace at /Users/sheehanolver/Projects/julia/src/stackwalk.c:94
record_backtrace at /Users/sheehanolver/Projects/julia/src/task.c:246 [inlined]
jl_throw at /Users/sheehanolver/Projects/julia/src/task.c:577
jl_rethrow_with_add at /Users/sheehanolver/Projects/julia/src/codegen.cpp:815
jl_compile_linfo at /Users/sheehanolver/Projects/julia/src/codegen.cpp:1172
jl_compile_method_internal at /Users/sheehanolver/Projects/julia/src/gf.c:1796
jl_fptr_trampoline at /Users/sheehanolver/Projects/julia/src/gf.c:1830
display_error at ./client.jl:102
jl_fptr_trampoline at /Users/sheehanolver/Projects/julia/src/gf.c:1831
jl_apply at /Users/sheehanolver/Projects/julia/src/./julia.h:1537 [inlined]
jl_f__apply at /Users/sheehanolver/Projects/julia/src/builtins.c:556
jl_f__apply_latest at /Users/sheehanolver/Projects/julia/src/builtins.c:594
#invokelatest#1 at ./essentials.jl:697 [inlined]
invokelatest at ./essentials.jl:696 [inlined]
_start at ./client.jl:427
true_main at /Users/sheehanolver/Projects/julia/usr/bin/julia (unknown line)
main at /Users/sheehanolver/Projects/julia/usr/bin/julia (unknown line)
```
What's the right way to "start from scratch" apart from wiping the entire `.julia` folder?

**Comment by stevengj** [comment]
Re-run `Pkg.build("PyCall")` after wiping the `.julia/conda` directory.

**Comment by milankl** [comment]
> Re-run `Pkg.build("PyCall")` after wiping the `.julia/conda` directory.

This also solved a problem that I had with my `NetCDF` build
```julia
(v1.3) pkg> build NetCDF
  Building Conda ─→ `~/.julia/packages/Conda/3rPhK/deps/build.log`
  Building NetCDF → `~/.julia/packages/NetCDF/dmH61/deps/build.log`
┌ Error: Error building `NetCDF`: 
│ Traceback (most recent call last):
│   File "/home/kloewer/.julia/conda/3/bin/conda", line 12, in <module>
│     from conda.cli import main
│ ModuleNotFoundError: No module named 'conda'
│ ERROR: LoadError: failed process:
```

**Comment by stevengj** [comment]
Seems like this can be closed as it's more a question than an issue.

**Comment by Balinus** [comment]
> > Re-run `Pkg.build("PyCall")` after wiping the `.julia/conda` directory.
> 
> This also solved a problem that I had with my `NetCDF` build
> 
> ```julia
> (v1.3) pkg> build NetCDF
>   Building Conda ─→ `~/.julia/packages/Conda/3rPhK/deps/build.log`
>   Building NetCDF → `~/.julia/packages/NetCDF/dmH61/deps/build.log`
> ┌ Error: Error building `NetCDF`: 
> │ Traceback (most recent call last):
> │   File "/home/kloewer/.julia/conda/3/bin/conda", line 12, in <module>
> │     from conda.cli import main
> │ ModuleNotFoundError: No module named 'conda'
> │ ERROR: LoadError: failed process:
> ```

Had the same error. Perhaps this should be added to the README? I'm gonna do a PR.
