### ISSUE TITLE
miniconda error for Windows 10:  ImportError: cannot import name 'CondaError'

### ISSUE THREAD

**Issue by Datseris** [JuliaPy/Conda.jl#161]
Seems to me, no matter what I try, I can't use PyCall with the "dedicated Julia miniconda":

```

julia> ENV["PYTHON"] = ""
""

(v1.2) pkg> add PyCall
  Updating registry at `C:\Users\datseris\.julia\registries\General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
 Resolving package versions...
  Updating `C:\Users\datseris\.julia\environments\v1.2\Project.toml`
  [438e738f] + PyCall v1.91.2
  Updating `C:\Users\datseris\.julia\environments\v1.2\Manifest.toml`
  [438e738f] + PyCall v1.91.2

(v1.2) pkg> add Conda
 Resolving package versions...
  Updating `C:\Users\datseris\.julia\environments\v1.2\Project.toml`
  [8f4d0f93] + Conda v1.3.0
  Updating `C:\Users\datseris\.julia\environments\v1.2\Manifest.toml`
 [no changes]

(v1.2) pkg> build PyCall
  Building Conda ─→ `C:\Users\datseris\.julia\packages\Conda\kLXeC\deps\build.log`
  Building PyCall → `C:\Users\datseris\.julia\packages\PyCall\ttONZ\deps\build.log`
┌ Error: Error building `PyCall`:
│ Traceback (most recent call last):
│   File "C:\Users\datseris\.julia\conda\3\Scripts\conda-script.py", line 10, in <module>
│     sys.exit(main())
│   File "C:\Users\datseris\.julia\conda\3\lib\site-packages\conda\cli\main.py", line 112, in main
│     from ..exceptions import conda_exception_handler
│   File "C:\Users\datseris\.julia\conda\3\lib\site-packages\conda\exceptions.py", line 12, in <module>
│     from . import CondaError, CondaExitZero, CondaMultiError, text_type
│ ImportError: cannot import name 'CondaError'
│ ┌ Info: Using the Python distribution in the Conda package by default.
│ └ To use a different Python version, set ENV["PYTHON"]="pythoncommand" and re-run Pkg.build("PyCall").
│ [ Info: Running `conda install -y numpy` in root environment
│ ERROR: LoadError: failed process: Process(setenv(`'C:\Users\datseris\.julia\conda\3\Scripts\conda.exe' install -y numpy`,["PATH=C:\\ProgramData\\Oracle\\Java\\javapath;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files\\Lenovo\\Touch Fingerprint Software\\;C:\\Program Files (x86)\\Common Files\\Lenovo;C:\\ProgramData\\Lenovo\\ReadyApps;C:\\Program Files (x86)\\PuTTY\\;C:\\Program Files\\OpenVPN\\bin;C:\\Program Files\\Git\\cmd;C:\\Users\\datseris\\AppData\\Local\\Pandoc\\;C:\\Program Files (x86)\\MuseScore 2\\bin;C:\\Program Files\\MuseScore 3\\bin;C:\\Program Files\\Intel\\WiFi\\bin\\;C:\\Program Files\\Common Files\\Intel\\WirelessCommon\\;C:\\Users\\datseris\\AppData\\Local\\Julia-1.2.0\\bin;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Ruby25-x64\\bin;C:\\texlive\\2018\\bin\\win32;C:\\Users\\datseris\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\datseris\\AppData\\Local\\Programs\\MiKTeX 2.9\\miktex\\bin\\x64\\;C:\\Program Files\\FFmpeg\\bin;C:\\Program Files\\Intel\\WiFi\\bin\\;C:\\Program Files\\Common Files\\Intel\\WirelessCommon\\;C:\\Users\\datseris\\AppData\\Local\\atom\\bin", "USERDOMAIN_ROAMINGPROFILE=ILAK", "SWSHARE=C:\\SWSHARE", "HOMEPATH=\\Users\\datseris", "PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.RB;.RBW", "SESSIONNAME=Console", "SYSTEMROOT=C:\\WINDOWS", "APPDATA=C:\\Users\\datseris\\AppData\\Roaming", "PSMODULEPATH=C:\\WINDOWS\\system32\\WindowsPowerShell\\v1.0\\Modules\\", "COMMONPROGRAMW6432=C:\\Program Files\\Common Files"  …  "COMMONPROGRAMFILES=C:\\Program Files\\Common Files", "ONEDRIVE=C:\\Users\\datseris\\OneDrive", "PROGRAMFILES(X86)=C:\\Program Files (x86)", "PROGRAMFILES=C:\\Program Files", "LOGONSERVER=\\\\ILAK", "CONDA_PREFIX=C:\\Users\\datseris\\.julia\\conda\\3", "JULIA_LOAD_PATH=@;C:\\Users\\datseris\\AppData\\Local\\Temp\\jl_4f6re7", "SYSTEMDRIVE=C:", "PROCESSOR_ARCHITECTURE=AMD64", "OPENBLAS_MAIN_FREE=1"]), ProcessExited(1)) [1]
│
│ Stacktrace:
│  [1] pipeline_error at .\process.jl:813 [inlined]
│  [2] #run#536(::Bool, ::typeof(run), ::Cmd) at .\process.jl:728
│  [3] run at .\process.jl:726 [inlined]
│  [4] runconda(::Cmd, ::String) at C:\Users\datseris\.julia\packages\Conda\kLXeC\src\Conda.jl:113
│  [5] #add#1(::String, ::typeof(Conda.add), ::String, ::String) at C:\Users\datseris\.julia\packages\Conda\kLXeC\src\Conda.jl:184
│  [6] add at C:\Users\datseris\.julia\packages\Conda\kLXeC\src\Conda.jl:183 [inlined] (repeats 2 times)
│  [7] top-level scope at C:\Users\datseris\.julia\packages\PyCall\ttONZ\deps\build.jl:84
│  [8] include at .\boot.jl:328 [inlined]
│  [9] include_relative(::Module, ::String) at .\loading.jl:1094
│  [10] include(::Module, ::String) at .\Base.jl:31
│  [11] include(::String) at .\client.jl:431
│  [12] top-level scope at none:5
│ in expression starting at C:\Users\datseris\.julia\packages\PyCall\ttONZ\deps\build.jl:43
└ @ Pkg.Operations C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.2\Pkg\src\backwards_compatible_isolation.jl:647
```

on Julia 1.2.0 and Windows 10.

**Comment by stevengj** [comment]
Is this in a fresh installation?   Maybe try a `Conda.update()`?

**Comment by Datseris** [comment]
I can't reproduce this error anymore. Unfortunately I am not sure what was the problem..., but on fresh installations now installing PyCall and python packages seems to work fine.
